apiVersion: apps/v1
kind: Deployment
metadata:
  name: googleclothes-deployment
  labels:
    app: googleclothes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googleclothes
  template:
    metadata:
      labels:
        app: googleclothes
    spec:
      containers:
      - name: googleclothes
        image: 600865094900.dkr.ecr.us-east-1.amazonaws.com/shopping-site-googleclothes
        ports:
        - containerPort: 80
