apiVersion: apps/v1
kind: Deployment
metadata:
  name: electronics-deployment
  labels:
    app: electronics
spec:
  replicas: 2
  selector:
    matchLabels:
      app: electronics
  template:
    metadata:
      labels:
        app: electronics
    spec:
      containers:
      - name: electronics
        image: 590184081927.dkr.ecr.us-east-1.amazonaws.com/shopping-site-electronics:03748eb66047df877094bdd816ddb77024d4831d
        ports:
        - containerPort: 80
