apiVersion: v1
kind: Service
metadata:
  name: main-service
  labels:
    app: main-frontend
spec:
  type: LoadBalancer
  selector:
    app: main-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80





