apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlemusic-deployment
  labels:
    app: googlemusic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlemusic
  template:
    metadata:
      labels:
        app: googlemusic
    spec:
      containers:
      - name: googlemusic
        image: 590184081927.dkr.ecr.us-east-1.amazonaws.com/shopping-site-googlemusic:03748eb66047df877094bdd816ddb77024d4831d
        ports:
        - containerPort: 80
