apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlemusic-deployment
  labels:
    app: googlemusic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlemusic
  template:
    metadata:
      labels:
        app: googlemusic
    spec:
      containers:
      - name: googlemusic
        image: 600865094900.dkr.ecr.us-east-1.amazonaws.com/shopping-site-googlemusic:0a8f405a2f9b1fd93a52b6d8d2dec58875d64fa8
        ports:
        - containerPort: 80
