apiVersion: apps/v1
kind: Deployment
metadata:
  name: computers-deployment
  labels:
    app: computers
spec:
  replicas: 2
  selector:
    matchLabels:
      app: computers
  template:
    metadata:
      labels:
        app: computers
    spec:
      containers:
      - name: computers
        image: 590184081927.dkr.ecr.us-east-1.amazonaws.com/shopping-site-computers:03748eb66047df877094bdd816ddb77024d4831d
        ports:
        - containerPort: 80
