apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlepay-deployment
  labels:
    app: googlepay
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlepay
  template:
    metadata:
      labels:
        app: googlepay
    spec:
      containers:
      - name: googlepay
        image: 600865094900.dkr.ecr.us-east-1.amazonaws.com/shopping-site-googlepay:d91fe880a3c7b2828658b8b434d71c7576c140a0
        ports:
        - containerPort: 80
