apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlepay-deployment
  labels:
    app: googlepay
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlepay
  template:
    metadata:
      labels:
        app: googlepay
    spec:
      containers:
      - name: googlepay
        image: 600865094900.dkr.ecr.us-east-1.amazonaws.com/shopping-site-googlepay:d8e3e02e867bfcb2aec273cf7ff6ddc883856799
        ports:
        - containerPort: 80
